version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: "MyProject"
    restart: unless-stopped
    env_file: ".env"
    ports:
      - "${PGPORT}:${PGPORT}"  
  s3:
    image: minio/minio
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: minio server /data --console-address ":9001"
  redis:
    image: redis
    container_name: "redis"
    restart: unless-stopped
    env_file: ".env"
    command: redis-server --requirepass redis_secret
    ports:
      - "6379:6379"